dynup:
  ros__parameters:
    engine:
      end_pose:
        arm_extended_length: 0.3
        trunk_height: 0.4
        trunk_pitch: 0.13
        trunk_x_final: 0.0

      dynup_back:
        arms_angle_back: 113.75
        arm_side_offset_back: 0.148
        com_shift_1: 0.1
        com_shift_2: 0.066
        foot_angle: 67.97
        time_full_squat_legs: 0.236

      dynup_front:
        hands_pitch: -46.7
        leg_min_length_front: 0.298
        max_leg_angle: 77.64
        time_foot_ground_front: 0.032
        time_hands_rotate: 0.352
        time_hands_side: 0.1
        time_to_squat: 0.736
        time_torso_45: 0.256
        trunk_overshoot_angle_front: -6.16
        trunk_x_front: 0.035
        wait_in_squat_front: 0.032

      rise:
        rise_time: 2.0

    stabilizer:
      end_pause:
        active: True
        duration: 0
        timeout: 1.5
      trunk_pid:
        pitch:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: True
        roll:
          p: -0.3
          i: 0.0
          d: -0.005
          i_clamp_min: -0.25
          i_clamp_max: 0.25
          antiwindup: True
