image_publish_topic: '/image_raw'

balls_topic: 'balls_in_image'
obstacles_topic: 'obstacles_in_image'
lines_topic: 'line_mask_in_image'
goalposts_topic: 'goal_posts_in_image'
field_boundary_topic: 'field_boundary_in_image'

line_thickness: 10
