# Defining the vision sim parameter overrides

# Field
field_color_detector_use_hsv: true
dynamic_color_lookup_table_active: false
field_color_detector_lower_values_h: 40  # Lower bound for the field color detector hue
field_color_detector_lower_values_s: 8  # Lower bound for the field color detector saturation
field_color_detector_lower_values_v: 58  # Lower bound for the field color detector value/brightness
field_color_detector_upper_values_h: 72  # Upper bound for the field color detector hue
field_color_detector_upper_values_s: 255  # Upper bound for the field color detector saturation
field_color_detector_upper_values_v: 255  # Upper bound for the field color detector value/brightness

field_boundary_detector_roi_height: 4
field_boundary_detector_green_threshold: 157
field_boundary_detector_vertical_steps: 60

# Improve line detection in sim
white_color_detector_use_color_lookup_table: false # Should the white color detector use a color lookup table or a HSV range
white_color_detector_lower_values_h: 101  # Lower bound for the white color detector hue
white_color_detector_lower_values_s: 0  # Lower bound for the white color detector saturation
white_color_detector_lower_values_v: 158  # Lower bound for the white color detector value/brightness
white_color_detector_upper_values_h: 180  # Upper bound for the white color detector hue
white_color_detector_upper_values_s: 255  # Upper bound for the white color detector saturation
white_color_detector_upper_values_v: 255  # Upper bound for the white color detector value/brightness
line_detector_field_boundary_offset: -15  # Threshold in which we are also searching for lines over the field boundary

line_detector_use_line_mask: true

neural_network_type: 'yolo_opencv'
yolo_darknet_model_path: '2021_02_jonas_webotsonlyfov'  # Name of the yolo model
yolo_confidence_threshold: 0.98
