ball_fcnn_debug: false  # only active when true and vision/debug is true, too!
ball_fcnn_model_path: '/models/fcnn031'
ball_fcnn_threshold: .5  # minimal value for a candidate to be considered
ball_fcnn_expand_stepsize: 4
ball_fcnn_pointcloud_stepsize: 10
ball_fcnn_shuffle_candidate_list: false  # shuffles the list of possible candidate points
ball_fcnn_min_ball_diameter: 5
ball_fcnn_max_ball_diameter: 200
ball_fcnn_publish_output: false
ball_fcnn_publish_horizon_offset: 5

field_color_detector_path: '/config/color_spaces/f132.yaml'
field_color_detector_path_sim: '/config/color_spaces/simColor_interpolated.yaml'
field_color_detector_use_hsv_green: false
field_color_detector_hsv_lower_values_h: 46
field_color_detector_hsv_lower_values_s: 101
field_color_detector_hsv_lower_values_v: 12
field_color_detector_hsv_upper_values_h: 98
field_color_detector_hsv_upper_values_s: 255
field_color_detector_hsv_upper_values_v: 255

white_color_detector_lower_values_h: 0
white_color_detector_lower_values_s: 0
white_color_detector_lower_values_v: 190
white_color_detector_upper_values_h: 180
white_color_detector_upper_values_s: 103
white_color_detector_upper_values_v: 255

red_color_detector_lower_values_h: 154
red_color_detector_lower_values_s: 83
red_color_detector_lower_values_v: 34
red_color_detector_upper_values_h: 255
red_color_detector_upper_values_s: 255
red_color_detector_upper_values_v: 255

blue_color_detector_lower_values_h: 109
blue_color_detector_lower_values_s: 140
blue_color_detector_lower_values_v: 93
blue_color_detector_upper_values_h: 145
blue_color_detector_upper_values_s: 255
blue_color_detector_upper_values_v: 255

horizon_finder_vertical_steps: 30
horizon_finder_horizontal_steps: 30
horizon_finder_roi_height: 11
horizon_finder_roi_width: 5
horizon_finder_precision_pix: 5
horizon_finder_min_precision_pix: 3

vision_ball_classifier: 'fcnn'  # cascade, fcnn or dummy
vision_debug_image: false
vision_debug_image_msg: false
vision_field_mask_image: false
vision_parallelize: true
vision_use_sim_color: false
vision_ball_candidate_horizon_y_offset: 0
vision_ball_candidate_rating_threshold: 0.5
vision_debug_printer_classes: ''

line_detector_horizon_offset: 15
line_detector_linepoints_range: 10000
line_detector_blur_kernel_size: 9

obstacle_color_threshold: 50
obstacle_white_threshold: 50
obstacle_horizon_diff_threshold: 20
obstacle_candidate_horizon_offset: 30
obstacle_candidate_min_width: 30
obstacle_finder_step_length: 5

goalpost_expand_stepsize: 5
goalpost_white_threshold: 100

ROS_img_msg_topic: 'image_raw'
ROS_img_queue_size: 1
ROS_ball_msg_topic: 'ball_in_image'
ROS_fcnn_img_msg_topic: 'fcnn_image'
ROS_line_msg_topic: 'line_in_image'
ROS_obstacle_msg_topic: 'obstacles_in_image'

ball_finder_classify_threshold: 0.5
ball_finder_scale_factor: 1.1
ball_finder_min_neighbors: 1
ball_finder_min_size: 10

classifier_model_path: '/models/classifier_01'

cascade_classifier_path: '/classifier/cascadeNew.xml'

dynamic_color_space: true
dynamic_color_space_field_mask_image: false
dynamic_color_space_queue_max_size: 10
dynamic_color_space_threshold: 0.6
dynamic_color_space_kernel_radius: 1
