
  ########
  # MISC #
  ########

  init_mode: 4

  field_boundary_interpolation_steps: 1


  #############
  # ROS-Stuff #
  #############

  line_topic: 'line_relative'
  goal_topic: 'goals_simulated'
  fieldboundary_topic: 'field_boundary_relative'
  fieldboundary_in_image_topic: 'field_boundary_in_image'
  corners_topic: 'corners'
  tcrossings_topic: 'tcrossings'
  crosses_topic: 'crosses'

  publishing_frame: '/localization_estimate'

  pose_publishing_topic: 'pose'

  particle_publishing_topic: 'pose_particles'

  publishing_frequency: 25

  #################
  # Visualization #
  #################

  debug_visualization: true


  ###################
  # Particle Filter #
  ###################


  particle_number: 500
  resampling_interval: 15

  diffusion_x_std_dev: 0.8
  diffusion_y_std_dev: 0.8
  diffusion_t_std_dev: 0.5
  diffusion_multiplicator: 0.005

  drift_distance_to_direction: 0.5
  drift_roation_to_direction: 0.0
  drift_distance_to_distance: 0.05
  drift_roation_to_distance: 0.0
  drift_distance_to_rotation: 0.05
  drift_rotation_to_rotation: 0.0

  min_weight: 0.01
  min_resampling_weight: 0.5
  percentage_best_particles: 50

  distance_factor : 0.5
  lines_factor: 1
  goal_factor: 0
  field_boundary_factor: 0
  corners_factor : 0
  tcrossings_factor: 0
  crosses_factor : 0

  min_motion_linear: 0.0
  min_motion_angular: 0.0
  filter_only_with_motion: false

