imu_sensor_controller:
  type: imu_sensor_controller/ImuSensorController
  publish_rate: 1000

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

DynamixelController:
  type: bitbots_ros_control/DynamixelController
  joints:
      - HeadPan
      - HeadTilt
      - LShoulderPitch
      - LShoulderRoll
      - LElbow
      - RShoulderPitch
      - RShoulderRoll
      - RElbow
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKnee
      - LAnklePitch
      - LAnkleRoll
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKnee
      - RAnklePitch
      - RAnkleRoll

    Â© 2019 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
