---
# type will be used to cast the given input into
# the result will then be checked against the given options for validity
# if there are no options the given input will be accepted if it is castable

bot_id:
  options: [1, 2, 3, 4, 5, 6]
  type: int
  explanation: ""
team_id:
  options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 31, 32]
  type: int
  explanation: ""
team_color:
  options: [0, 1]
  type: int
  explanation: "0 is blue, 1 is red"
role:
  options: ['goalie', 'offense', 'defense', 'penalty']
  type: str
  explanation: ""
position_number:
  options: [0, 1, 2]
  type: str
  explanation: "0 = center, 1 = left, 2 = right"
monitoring_host_ip:
  type: ipaddress.IPv4Address
  explanation: "IP of monitoring host to send UDP messages to"
