# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - HeadPan
    - HeadTilt
    - LHipYaw
    - LHipRoll
    - LHipPitch
    - LKnee
    - LAnklePitch
    - LAnkleRoll
    - LShoulderPitch
    - LShoulderRoll
    - LElbow
    - RHipYaw
    - RHipRoll
    - RHipPitch
    - RKnee
    - RAnklePitch
    - RAnkleRoll
    - RShoulderPitch
    - RShoulderRoll
    - RElbow
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50