[package]
name = "bitbots_rust_test"
version = "0.1.0"
authors = ["Florian Vahl <git@flova.de>"]
edition = "2021"

[dependencies]
r2r = "0.9"
futures = "0.3.15"
tokio = { version = "1", features = ["full"] }
