global_costmap:
  plugins:
    - {name: obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # Set map origin to have the origin in the map center
  origin_x: -7.5
  origin_y: -7.5
  robot_base_frame: /base_footprint
  global_frame: /map

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.0
  rolling_window: false
  width: 15.0
  height: 15.0
  robot_radius: 0.2
