Animations:
  Kicks:
    leftKick: "kick_left"
    leftKickStrong: ""
    leftKickSide: ""
    rightKick: "kick_right"
    rightKickStrong: ""
    rightKickSide: ""

  Goalie:
    raiseLeftArm: ""
    raiseRightArm: ""
    raiseBothArms: ""
    # For throwing to the middle
    lowerBothArms: ""

    throwLeft: ""
    throwRight: ""
    throwMiddle: ""
    fallLeft: "goalie_falling_left"
    fallRight: "goalie_falling_right"

  Penalty:
    # Penalty kicks to the left/right
    leftKick: ""
    rightKick: ""
    # Penalty kicks to the front, with left/right leg
    frontLeftKick: ""
    frontRightKick: ""

  Misc:
    cheering: "cheering"
