walking:
  ros__parameters:
    engine:
      foot_put_down_z_offset: 0.0
      trunk_x_offset_p_coef_forward: 0.0
      trunk_x_offset_p_coef_turn: 0.0

      kick_length: 0.09
      kick_vel: 0.2
      kick_phase: 0.75

      double_support_ratio: 0.0264282002140171
      first_step_swing_factor: 1.80591386587488
      foot_distance: 0.179900277671633
      foot_rise: 0.0819786291304007
      freq: 1.96331645572213
      trunk_height: 0.394780002666927
      trunk_phase: -0.151653984431689
      trunk_pitch: 0.105566178884548
      trunk_pitch_p_coef_forward: -0.186068274875133
      trunk_pitch_p_coef_turn: -0.457339940581988
      trunk_swing: 0.154856652745882
      trunk_x_offset: 0.00885762700992359
      trunk_y_offset: 0.00369752824507733
      trunk_z_movement: 0.0155005052923747
      first_step_trunk_phase: -0.5
      foot_apex_phase: 0.5
      foot_overshoot_phase: 1.0
      foot_overshoot_ratio: 0.0
      foot_put_down_phase: 1.0
      foot_z_pause: 0.0
      trunk_pause: 0.0


    node:
      # update frequency of the engine
      engine_freq: 500.0

      # parameters for bioIK
      ik_timeout: 0.01
      ik_reset: True

      debug_active: False

      max_step_x: 10000.0
      max_step_y: 10000.0
      max_step_xy: 10000.0
      max_step_z: 100000.0
      max_step_angular: 10000.0

      x_speed_multiplier: 1.3
      y_speed_multiplier: 1.5
      yaw_speed_multiplier: 1.5

      imu_active: False
      imu_pitch_threshold: 0.19
      imu_roll_threshold: 0.4
      imu_pitch_vel_threshold: 1.3
      imu_roll_vel_threshold: 5.7
      pause_duration: 3.0

      pressure_phase_reset_active: False
      ground_min_pressure: 1.5
      phase_reset_phase: 0.25
      joint_min_effort: 35.0
      effort_phase_reset_active: False

pid_trunk_fused_pitch:
  ros__parameters:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
    i_clamp_min: 0.0
    i_clamp_max: 0.0
    antiwindup: False

pid_trunk_fused_roll:
  ros__parameters:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
    i_clamp_min: 0.0
    i_clamp_max: 0.0
    antiwindup: False
