walking:
  engine:

    foot_z_pause: 0.0
    trunk_pause: 0.0
    foot_put_down_phase: 1.0


    kick_length: 0.09
    kick_vel: 0.2
    kick_phase: 0.75


  node:
    # update frequency of the engine
    engine_freq: 1000.0

    # parameters for bioIK
    ik_timeout: 0.01

    debug_active: True

    trunkYOnlyInDoubleSupport: False

    max_step_x: 1000
    max_step_y: 1000
    max_step_xy: 1000
    max_step_z: 1000

    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    phase_reset_active: False
    ground_min_pressure: 1.5
    phase_reset_phase: 0.25
    joint_min_effort: 35
    effort_phase_reset_active: False

    publish_odom_tf: False

  pid_trunk_fused_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: False

  pid_trunk_fused_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: False
