walking:
  engine:
    double_support_ratio: 0.344712138054358
    first_step_swing_factor: 0.655732438779827
    foot_distance: 0.179014406520205
    foot_rise: 0.0691599578967284
    freq: 1.54162204748046
    trunk_height: 0.323123253829563
    trunk_phase: -0.0743933506894948
    trunk_pitch: 0.21401534769464
    trunk_pitch_p_coef_forward: 0.278779805055009
    trunk_pitch_p_coef_turn: 2.3824552096713
    trunk_swing: 0.359304758903818
    trunk_x_offset: -0.0495856564961475
    trunk_y_offset: 0.00109375178761593
    trunk_z_movement: 0.0731081454325577
    directions_left: 49.0
    early_termination_at: [-0.4, 0, -0.5]
    fall_sum: 0.0
    first_step_trunk_phase: -0.5
    foot_apex_phase: 0.5
    foot_overshoot_phase: 1
    foot_overshoot_ratio: 0.0
    foot_put_down_phase: 1
    foot_z_pause: 0
    gyro_obj: 0.006583455791882188
    last_pose_obj: 0.2759057237031307
    orientation_obj: 0.1545917664648956
    pose_obj: 0.11224960109409649
    stability_obj: 0.0805876111283889
    termination_reason: pose
    trunk_pause: 0
    s_nsga2:generation: 10.0
    s_nsga2:parents: [215322, 215250]

  node:
    # update frequency of the engine
    engine_freq: 1000

    # parameters for bioIK
    ik_timeout: 0.001

    debug_active: False

    trunkYOnlyInDoubleSupport: False

    max_step_x: 1000
    max_step_y: 1000
    max_step_xy: 1000
    max_step_z: 1000
    max_step_angular: 1000

    x_speed_multiplier: 1
    y_speed_multiplier: 1
    yaw_speed_multiplier: 1

    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    phase_reset_active: False
    ground_min_pressure: 1.5
    phase_reset_phase: 0.25
    joint_min_effort: 35
    effort_phase_reset_active: False

pid_trunk_pitch:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_trunk_roll:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_trunk_fused_pitch:
  ros__parameters:
    p: 0.0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_trunk_fused_roll:
  ros__parameters:
    p: 0.0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_trunk_gyro_roll:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_trunk_gyro_pitch:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_cop_x:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_cop_y:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_ankle_left_pitch:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_ankle_right_pitch:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_ankle_left_roll:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_ankle_right_roll:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_hip_pitch:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_hip_roll:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_foot_pos_x:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False

pid_foot_pos_y:
  ros__parameters:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
