walking:
  # Full walk cycle frequency
  # (in Hz, > 0)
  freq: 0.5
  # Length of double support phase in half cycle
  # (ratio, [0:1])
  double_support_ratio: 0.05
  # Lateral distance between the feet center
  # (in m, >= 0)
  foot_distance: 0.2
  # Maximum flying foot height
  # (in m, >= 0)
  foot_rise: 0.06
  # Pause of Z movement on highest point
  # (single support cycle ratio, [0,1])
  foot_z_pause: 0.0
  # Phase of flying foot apex
  # (single support cycle phase, [0:1])
  foot_apex_phase: 0.5
  # Let the foot's downward trajectory end above the ground
  # this is helpful if the support leg bends
  # (in m, >= 0)
  foot_put_down_z_offset: 0.0
  #Phase time for moving the foot from Z offset to ground
  #(in half cycle ratio [0:1])
  foot_put_down_phase: 1.0
  # Foot X/Y overshoot in ratio of step length
  # (ratio, >= 0)
  foot_overshoot_ratio: 0.1
  # Foot X/Y overshoot phase
  # (single support cycle phase, [foot_apex_phase:1]
  foot_overshoot_phase: 0.85
  # Height of the trunk from ground
  # (in m, > 0)
  trunk_height: 0.40
  # Trunk pitch orientation
  # (in rad)
  trunk_pitch: 0.0
  # Phase offset of trunk oscillation
  # (half cycle phase, [-1:1])
  trunk_phase: 0.0
  # Trunk forward offset
  # (in m)
  trunk_x_offset: 0.0
  # Trunk lateral offset
  # (in m)
  trunk_y_offset: 0.0
  # Trunk lateral oscillation amplitude ratio
  # (ratio, >= 0)
  trunkSwing: 0.2
  # Trunk swing pause length in phase at apex
  # (half cycle ratio, [0:1])
  trunk_pause: 0.0
  # Trunk forward offset proportional to forward step
  # (in 1)
  trunk_x_offset_p_coef_forward: 0.0
  # Trunk forward offset proportional to rotation step
  # (in m/rad)
  trunk_x_offset_p_coef_turn: 0.0
  # Trunk pitch orientation proportional to forward step
  # (in rad/m)
  trunk_pitch_p_coef_forward: 0.0
  # Trunk pitch orientation proportional to rotation step
  # (in 1)
  trunk_pitch_p_coef_turn: 0.0

  # update frequency of the engine
  engine_freq: 200.0
  
  # parameters for bioIK
  bio_ik_time: 0.01

  debug_active: True

  kick_length: 0.09
  kick_vel: 0.2
  kick_phase: 0.75


  trunkYOnlyInDoubleSupport: False

  max_step_x: 0.06
  max_step_y: 0.05
  max_step_xy: 0.09
  max_step_z: 0.45

  vel: -1
  acc: -1
  pwm: -1

  imu_active: True
  imu_pitch_threshold: 0.5
  imu_roll_threshold: 0.4
  imu_pitch_vel_threshold: 1.1
  imu_roll_vel_threshold: 1.0
  pause_duration: 0.5

  publishOdomTF: False

  first_step_swing_factor: 1.0