[package]
name = "bitbots_rust_nav"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "==0.4.0" }

[package.host-dependencies]
rust = ">=1.91.1,<1.92"
maturin = ">=1.10.2,<2"
python = "==3.12"
